namespace Eumel.Dj.Mobile.Data
{
    // Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
    // If you change the class to 'public' in order to use it outside its assembly
    //  you should also change the fields from 'const' to 'public static readonly'
    public static class IconFont
    {
        public const string WeatherLightningRainy = "\U000f067e";
        public const string Refresh = "\U000f0450";
        public const string Heart = "\U000f02d1";
        public const string HeartBroken = "\U000f02d4";
    }
}